name: pixelfield
description: a new PixelField Project


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.15
  #json serializable is a good library if you need to create jsonDecodeClass,
  #even for the small project i prefer to use it in order to don't make syntax
  #mistakes and loose time
  json_serializable: ^6.5.4

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  #i used this library to load the home screen as you create in Figma
flutter_native_splash:

  background_image: "assets/images/background.png"
  image: "assets/icon/iconXl.png"




  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  #in order to have the icons on the screen i used this library
  flutter_launcher_icons: "^0.11.0"



flutter:


  uses-material-design: true

# in order to load json and pictures
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: EBGaramond
      fonts:
        - asset: assets/fonts/EBGaramond-VariableFont_wght.ttf
#i used this font because i found it on your Figma, i prefered to be precise
